[package]
name = "kakasi-dict"
version = "0.1.0"
edition = "2021"
authors = ["ThetaDev"]
license = "GPL-3.0"
description = "Dictionary for kakasi"

[dependencies]
phf = "0.11.1"
phf_shared = "0.11.1"
